### PR TITLE
wp-4676 : adjusted entry point and dependencies.

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
## Issue
When attempting a dry run publish of this package to the public repo, we see the following warning:
```shell
The name of "lib/opentracing_dart.dart", "opentracing_dart", should match the name of the package, "opentracing".
This helps users know what library to import.
```

## Changes
- Adjusted entry point for library.
- Adjusted dependencies to be compatible with latest Dart SDK.

**Tests:**
- n/a

## Areas of Regression
- failing pub deployments

## Testing
- verify that the bin directory is in the tar ball on the associated smithy build.

## Code Review
@macleodbroad-wf @danielharasymiw-wf  @sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by macleodbroad-wf** [comment]
lgtm +1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by danielharasymiw-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
QA +1

- [x] Dev +1's
- [x] Build Passes
- [x] All unit tests pass

@Workiva/release-management-pp

**Comment by colefeisthamel-wf** [comment]
RM +1 clean build and deps in latest release PR #43

**Pull request merged**
