### PR TITLE
Release opentracing_dart 1.0.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [CPLAT-4198 : added Meta dependency](https://github.com/Workiva/opentracing_dart/pull/38)

Requested by: @dustin.pauze

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/opentracing_dart/compare/1.0.0...Workiva:release_opentracing_dart_1.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/opentracing_dart/compare/1.0.0...1.0.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4622718901682176/logs/)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by dustinlessard-wf** [comment]
QA +1

@Workiva/release-management-pp

**Comment by dustinlessard-wf** [comment]
@Workiva/release-management-pp

**Comment by dancleereman-wf** [comment]
@dustinlessard-wf - this still needs a code review.  Can you get one done posthumously to avoid any approval issues come release-time?

**Pull request merged**
