### PR TITLE
Adds analysis options

### PR DESCRIPTION
**Pull request by macleodbroad-wf**
R: @danielharasymiw-wf @dustinlessard-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by danielharasymiw-wf** [comment]
Ran `pub dart_dev analyze`:
`::: dartanalyzer --fatal-warnings --fatal-hints --strong lib/opentracing_dart.dart (treating hints as fatal)
    Analyzing lib/opentracing_dart.dart...
    No issues found!

Analysis completed.1

QA +1

**Pull request merged**
