### PR TITLE
Revert "Adds setter to abstract class"

### PR DESCRIPTION
**Pull request by macleodbroad-wf**
This reverts commit e097d7bf66ea87c19d817b3223522ef03343130e.

R: @dustinlessard-wf @sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master
@Workiva/release-management-pp

**Comment by colefeisthamel-wf** [comment]
RM +1 clean build and deps in latest release PR #43

**Pull request merged**
