### PR TITLE
DS-6121 : Release opentracing_dart 0.2.0

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:

Requested by: @dustinlessard-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/opentracing_dart/compare/0.1.3...version-bump-opentracing_dart-0-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/opentracing_dart/compare/0.1.3...0.2.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by dustinlessard-wf** [comment]
+1

**Comment by macleodbroad-wf** [comment]
+1

**Comment by danielharasymiw-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master
@Workiva/release-management-pp

**Pull request merged**
