### PR TITLE
WP-4616 : adjusted pub spec

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
Purpose
-------

We don't have the right version in our pubspec.

Solution
--------

We now have the right version in our pubspec.

Semantic Versioning (check one)
-------------------------------
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch release

How to QA
-------
- [x] run unit-tests
- [x] run integration tests

**Required:**
@macleodbroad-wf  @danielharasymiw-wf  @sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
Once this is in, we can make a proper release and push a proper version to the OSS pub server.

**Comment by danielharasymiw-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie has run and reports properly the release the ticket will be included in
- [x] Rosie reports a clean dependency scan

Merging into master
@Workiva/release-management-pp

**Comment by colefeisthamel-wf** [comment]
RM +1 clean build and deps in latest release PR #43

**Pull request merged**
